/* Kier — generated by web/generate.py from core/palette/kier.json.
   Inlined rather than fetched so the page works from file://. */
window.KIER = {
 "name": "Kier",
 "version": "1.0.0",
 "accentOrder": [
  "blush",
  "cherry",
  "coral",
  "tangerine",
  "amber",
  "brass",
  "avocado",
  "moss",
  "lagoon",
  "denim",
  "iris",
  "plum"
 ],
 "neutralOrder": [
  "crust",
  "mantle",
  "base",
  "surface0",
  "surface1",
  "surface2",
  "overlay0",
  "overlay1",
  "overlay2",
  "subtext0",
  "subtext1",
  "text"
 ],
 "defaultAccent": "tangerine",
 "roleCount": 58,
 "aliasCount": 33,
 "aliases": [
  [
   "number",
   "constant"
  ],
  [
   "number",
   "boolean"
  ],
  [
   "constant",
   "boolean"
  ],
  [
   "constant",
   "constant.builtin"
  ],
  [
   "type",
   "type.builtin"
  ],
  [
   "type",
   "class"
  ],
  [
   "keyword",
   "keyword.control"
  ],
  [
   "keyword",
   "storage"
  ],
  [
   "keyword",
   "modifier"
  ],
  [
   "function",
   "function.method"
  ],
  [
   "function",
   "function.builtin"
  ],
  [
   "character",
   "string"
  ],
  [
   "keyword.operator",
   "operator"
  ],
  [
   "type",
   "namespace"
  ],
  [
   "namespace",
   "type.builtin"
  ],
  [
   "variable",
   "type"
  ],
  [
   "variable",
   "operator"
  ],
  [
   "variable",
   "variable.parameter"
  ],
  [
   "variable",
   "function.call"
  ],
  [
   "type",
   "operator"
  ],
  [
   "type",
   "variable.parameter"
  ],
  [
   "type",
   "class"
  ],
  [
   "type",
   "interface"
  ],
  [
   "type",
   "function.call"
  ],
  [
   "operator",
   "variable.parameter"
  ],
  [
   "operator",
   "function.call"
  ],
  [
   "variable.parameter",
   "function.call"
  ],
  [
   "class",
   "interface"
  ],
  [
   "markup.bold",
   "markup.italic"
  ],
  [
   "number",
   "constant.builtin"
  ],
  [
   "keyword",
   "keyword.import"
  ],
  [
   "keyword",
   "tag"
  ],
  [
   "string",
   "markup.code"
  ]
 ],
 "flavours": {
  "groove": {
   "id": "groove",
   "name": "Groove",
   "order": 1,
   "reference": "\"Groove Is in the Heart\" (1990)",
   "blurb": "The anthem. Hardest contrast, purest orange, nothing held back.",
   "accent": "#FE8019",
   "neutrals": {
    "crust": {
     "hex": "#131515",
     "contrast": 1.12
    },
    "mantle": {
     "hex": "#181A1B",
     "contrast": 1.07
    },
    "base": {
     "hex": "#1D2021",
     "contrast": 1.0
    },
    "surface0": {
     "hex": "#282828",
     "contrast": 1.11
    },
    "surface1": {
     "hex": "#32302F",
     "contrast": 1.25
    },
    "surface2": {
     "hex": "#3C3836",
     "contrast": 1.41
    },
    "overlay0": {
     "hex": "#7C6F64",
     "contrast": 3.37
    },
    "overlay1": {
     "hex": "#928474",
     "contrast": 4.51
    },
    "overlay2": {
     "hex": "#A89984",
     "contrast": 5.9
    },
    "subtext0": {
     "hex": "#C3B396",
     "contrast": 7.97
    },
    "subtext1": {
     "hex": "#D7C7A4",
     "contrast": 9.83
    },
    "text": {
     "hex": "#EBDBB2",
     "contrast": 11.95
    }
   },
   "accents": {
    "blush": {
     "hex": "#CB7690",
     "contrast": 5.1
    },
    "cherry": {
     "hex": "#CB7679",
     "contrast": 5.0
    },
    "coral": {
     "hex": "#CA7F68",
     "contrast": 5.27
    },
    "tangerine": {
     "hex": "#FE8019",
     "contrast": 6.49
    },
    "amber": {
     "hex": "#DCAF56",
     "contrast": 8.05
    },
    "brass": {
     "hex": "#D2BB60",
     "contrast": 8.6
    },
    "avocado": {
     "hex": "#BBC86A",
     "contrast": 9.04
    },
    "moss": {
     "hex": "#86C86A",
     "contrast": 8.19
    },
    "lagoon": {
     "hex": "#6AC8B0",
     "contrast": 8.2
    },
    "denim": {
     "hex": "#6AACC8",
     "contrast": 6.52
    },
    "iris": {
     "hex": "#768DCB",
     "contrast": 5.03
    },
    "plum": {
     "hex": "#CA72B0",
     "contrast": 5.11
    }
   },
   "textContrast": 12.0,
   "minAccent": {
    "token": "cherry",
    "ratio": 5.0
   },
   "ansi": {
    "black": "#32302F",
    "white": "#D7C7A4",
    "red": "#F93E44",
    "green": "#7BE44E",
    "yellow": "#F9CC39",
    "blue": "#6CABC6",
    "magenta": "#D85AB2",
    "cyan": "#64CEB4",
    "bright_red": "#FA6166",
    "bright_green": "#93E96E",
    "bright_yellow": "#FAD55D",
    "bright_blue": "#86BAD0",
    "bright_magenta": "#DF78C0",
    "bright_cyan": "#80D7C2",
    "bright_white": "#EBDBB2",
    "bright_black": "#3C3836"
   }
  },
  "clique": {
   "id": "clique",
   "name": "Clique",
   "order": 2,
   "reference": "World Clique (1990)",
   "blurb": "The debut. Deep oxide over the darkest ground in the set.",
   "accent": "#BC5230",
   "neutrals": {
    "crust": {
     "hex": "#100E0D",
     "contrast": 1.07
    },
    "mantle": {
     "hex": "#141210",
     "contrast": 1.04
    },
    "base": {
     "hex": "#191614",
     "contrast": 1.0
    },
    "surface0": {
     "hex": "#231F1D",
     "contrast": 1.1
    },
    "surface1": {
     "hex": "#2E2927",
     "contrast": 1.25
    },
    "surface2": {
     "hex": "#3A3431",
     "contrast": 1.47
    },
    "overlay0": {
     "hex": "#847768",
     "contrast": 4.13
    },
    "overlay1": {
     "hex": "#9A8C7F",
     "contrast": 5.52
    },
    "overlay2": {
     "hex": "#B0A296",
     "contrast": 7.25
    },
    "subtext0": {
     "hex": "#C4B8AD",
     "contrast": 9.27
    },
    "subtext1": {
     "hex": "#D4C8BE",
     "contrast": 10.98
    },
    "text": {
     "hex": "#E3D9CF",
     "contrast": 12.94
    }
   },
   "accents": {
    "blush": {
     "hex": "#C46E88",
     "contrast": 5.09
    },
    "cherry": {
     "hex": "#C57275",
     "contrast": 5.18
    },
    "coral": {
     "hex": "#C8806A",
     "contrast": 5.79
    },
    "tangerine": {
     "hex": "#C4966E",
     "contrast": 6.8
    },
    "amber": {
     "hex": "#CAA968",
     "contrast": 8.05
    },
    "brass": {
     "hex": "#C4B36E",
     "contrast": 8.59
    },
    "avocado": {
     "hex": "#B8C46E",
     "contrast": 9.57
    },
    "moss": {
     "hex": "#88C46E",
     "contrast": 8.72
    },
    "lagoon": {
     "hex": "#6EC4AE",
     "contrast": 8.72
    },
    "denim": {
     "hex": "#6EAAC4",
     "contrast": 7.04
    },
    "iris": {
     "hex": "#7288C5",
     "contrast": 5.18
    },
    "plum": {
     "hex": "#C46EAA",
     "contrast": 5.28
    }
   },
   "textContrast": 12.9,
   "minAccent": {
    "token": "blush",
    "ratio": 5.09
   },
   "ansi": {
    "black": "#2E2927",
    "white": "#D4C8BE",
    "red": "#F93940",
    "green": "#7EDD55",
    "yellow": "#F6CB3C",
    "blue": "#70A9C2",
    "magenta": "#D260B0",
    "cyan": "#69C9B1",
    "bright_red": "#FA5D62",
    "bright_green": "#95E374",
    "bright_yellow": "#F8D45F",
    "bright_blue": "#8AB8CD",
    "bright_magenta": "#DA7DBE",
    "bright_cyan": "#84D3BF",
    "bright_white": "#E3D9CF",
    "bright_black": "#3A3431"
   }
  },
  "dewdrop": {
   "id": "dewdrop",
   "name": "Dewdrop",
   "order": 3,
   "reference": "Dewdrops in the Garden (1994)",
   "blurb": "Soft, warm and fully resolved. The gentlest of the five.",
   "accent": "#E89C5D",
   "neutrals": {
    "crust": {
     "hex": "#171514",
     "contrast": 1.14
    },
    "mantle": {
     "hex": "#1E1B19",
     "contrast": 1.07
    },
    "base": {
     "hex": "#24211E",
     "contrast": 1.0
    },
    "surface0": {
     "hex": "#35302B",
     "contrast": 1.23
    },
    "surface1": {
     "hex": "#46403A",
     "contrast": 1.57
    },
    "surface2": {
     "hex": "#575048",
     "contrast": 2.02
    },
    "overlay0": {
     "hex": "#8E8271",
     "contrast": 4.26
    },
    "overlay1": {
     "hex": "#A39682",
     "contrast": 5.52
    },
    "overlay2": {
     "hex": "#B9AB94",
     "contrast": 7.1
    },
    "subtext0": {
     "hex": "#CBBDA7",
     "contrast": 8.68
    },
    "subtext1": {
     "hex": "#D8CBB5",
     "contrast": 10.01
    },
    "text": {
     "hex": "#E5D9C3",
     "contrast": 11.47
    }
   },
   "accents": {
    "blush": {
     "hex": "#CF8199",
     "contrast": 5.53
    },
    "cherry": {
     "hex": "#CF8184",
     "contrast": 5.43
    },
    "coral": {
     "hex": "#D68F7A",
     "contrast": 6.15
    },
    "tangerine": {
     "hex": "#E89C5D",
     "contrast": 7.13
    },
    "amber": {
     "hex": "#E4BC6C",
     "contrast": 8.93
    },
    "brass": {
     "hex": "#DBC775",
     "contrast": 9.49
    },
    "avocado": {
     "hex": "#C5CF81",
     "contrast": 9.62
    },
    "moss": {
     "hex": "#99CF81",
     "contrast": 8.84
    },
    "lagoon": {
     "hex": "#81CFBC",
     "contrast": 8.83
    },
    "denim": {
     "hex": "#81B8CF",
     "contrast": 7.39
    },
    "iris": {
     "hex": "#8196CF",
     "contrast": 5.49
    },
    "plum": {
     "hex": "#CF81B8",
     "contrast": 5.71
    }
   },
   "textContrast": 11.5,
   "minAccent": {
    "token": "cherry",
    "ratio": 5.43
   },
   "ansi": {
    "black": "#46403A",
    "white": "#D8CBB5",
    "red": "#FA575C",
    "green": "#8FE76A",
    "yellow": "#FAD457",
    "blue": "#83B7CE",
    "magenta": "#DC74BD",
    "cyan": "#7CD4BE",
    "bright_red": "#FB7579",
    "bright_green": "#A3EB85",
    "bright_yellow": "#FBDC75",
    "bright_blue": "#99C4D7",
    "bright_magenta": "#E28DC9",
    "bright_cyan": "#94DCCA",
    "bright_white": "#E5D9C3",
    "bright_black": "#575048"
   }
  },
  "infinity": {
   "id": "infinity",
   "name": "Infinity",
   "order": 4,
   "reference": "Infinity Within (1992)",
   "blurb": "Cool grey ground, warm accent. Contrast by temperature, not brightness.",
   "accent": "#E07A3C",
   "neutrals": {
    "crust": {
     "hex": "#111212",
     "contrast": 1.09
    },
    "mantle": {
     "hex": "#151617",
     "contrast": 1.05
    },
    "base": {
     "hex": "#1A1B1C",
     "contrast": 1.0
    },
    "surface0": {
     "hex": "#232527",
     "contrast": 1.12
    },
    "surface1": {
     "hex": "#2E3033",
     "contrast": 1.3
    },
    "surface2": {
     "hex": "#3A3D40",
     "contrast": 1.58
    },
    "overlay0": {
     "hex": "#7C8285",
     "contrast": 4.43
    },
    "overlay1": {
     "hex": "#92989A",
     "contrast": 5.9
    },
    "overlay2": {
     "hex": "#A8ADAF",
     "contrast": 7.61
    },
    "subtext0": {
     "hex": "#BFC3C4",
     "contrast": 9.71
    },
    "subtext1": {
     "hex": "#D1D4D3",
     "contrast": 11.56
    },
    "text": {
     "hex": "#E2E4E3",
     "contrast": 13.5
    }
   },
   "accents": {
    "blush": {
     "hex": "#CB869A",
     "contrast": 6.09
    },
    "cherry": {
     "hex": "#CB8688",
     "contrast": 6.0
    },
    "coral": {
     "hex": "#CB9686",
     "contrast": 6.77
    },
    "tangerine": {
     "hex": "#E07A3C",
     "contrast": 5.76
    },
    "amber": {
     "hex": "#CBB486",
     "contrast": 8.55
    },
    "brass": {
     "hex": "#CBBD86",
     "contrast": 9.17
    },
    "avocado": {
     "hex": "#C2CB86",
     "contrast": 10.0
    },
    "moss": {
     "hex": "#9ACB86",
     "contrast": 9.25
    },
    "lagoon": {
     "hex": "#84CDBB",
     "contrast": 9.39
    },
    "denim": {
     "hex": "#78BCD9",
     "contrast": 8.21
    },
    "iris": {
     "hex": "#8498CD",
     "contrast": 6.04
    },
    "plum": {
     "hex": "#CB86B6",
     "contrast": 6.26
    }
   },
   "textContrast": 13.5,
   "minAccent": {
    "token": "tangerine",
    "ratio": 5.76
   },
   "ansi": {
    "black": "#2E3033",
    "white": "#D1D4D3",
    "red": "#F65A60",
    "green": "#92E071",
    "yellow": "#F4D15D",
    "blue": "#77BBD9",
    "magenta": "#D77ABB",
    "cyan": "#81D0BC",
    "bright_red": "#F8787D",
    "bright_green": "#A6E68B",
    "bright_yellow": "#F6D97A",
    "bright_blue": "#8FC7E0",
    "bright_magenta": "#DE92C7",
    "bright_cyan": "#98D8C8",
    "bright_white": "#E2E4E3",
    "bright_black": "#3A3D40"
   }
  },
  "runaway": {
   "id": "runaway",
   "name": "Runaway",
   "order": 5,
   "reference": "\"Runaway\" (1992)",
   "blurb": "Colour runs from the interface. Only the signal stays lit.",
   "accent": "#A89984",
   "neutrals": {
    "crust": {
     "hex": "#121211",
     "contrast": 1.09
    },
    "mantle": {
     "hex": "#171615",
     "contrast": 1.05
    },
    "base": {
     "hex": "#1C1B1A",
     "contrast": 1.0
    },
    "surface0": {
     "hex": "#262524",
     "contrast": 1.12
    },
    "surface1": {
     "hex": "#322F2D",
     "contrast": 1.29
    },
    "surface2": {
     "hex": "#3E3A37",
     "contrast": 1.53
    },
    "overlay0": {
     "hex": "#867D71",
     "contrast": 4.25
    },
    "overlay1": {
     "hex": "#9B9285",
     "contrast": 5.6
    },
    "overlay2": {
     "hex": "#B0A79A",
     "contrast": 7.24
    },
    "subtext0": {
     "hex": "#C5BDB1",
     "contrast": 9.24
    },
    "subtext1": {
     "hex": "#D4CEC2",
     "contrast": 10.98
    },
    "text": {
     "hex": "#E4DED3",
     "contrast": 12.85
    }
   },
   "accents": {
    "blush": {
     "hex": "#C68B9D",
     "contrast": 6.21
    },
    "cherry": {
     "hex": "#C9888A",
     "contrast": 6.04
    },
    "coral": {
     "hex": "#D7907A",
     "contrast": 6.68
    },
    "tangerine": {
     "hex": "#FE8019",
     "contrast": 6.81
    },
    "amber": {
     "hex": "#DCBA75",
     "contrast": 9.27
    },
    "brass": {
     "hex": "#D5C37C",
     "contrast": 9.77
    },
    "avocado": {
     "hex": "#C2CB86",
     "contrast": 9.98
    },
    "moss": {
     "hex": "#9DC48D",
     "contrast": 8.77
    },
    "lagoon": {
     "hex": "#88C9B9",
     "contrast": 9.09
    },
    "denim": {
     "hex": "#88B6C9",
     "contrast": 7.85
    },
    "iris": {
     "hex": "#8D9BC4",
     "contrast": 6.24
    },
    "plum": {
     "hex": "#C48DB3",
     "contrast": 6.39
    }
   },
   "textContrast": 12.8,
   "minAccent": {
    "token": "cherry",
    "ratio": 6.04
   },
   "ansi": {
    "black": "#322F2D",
    "white": "#D4CEC2",
    "red": "#E76A6E",
    "green": "#97D57C",
    "yellow": "#E5C86C",
    "blue": "#87B6CA",
    "magenta": "#CD83B7",
    "cyan": "#89C8B8",
    "bright_red": "#EB8588",
    "bright_green": "#AADD94",
    "bright_yellow": "#EAD286",
    "bright_blue": "#9DC3D4",
    "bright_magenta": "#D699C4",
    "bright_cyan": "#9ED2C5",
    "bright_white": "#E4DED3",
    "bright_black": "#3E3A37"
   }
  }
 },
 "ecosystems": {
  "textmate": {
   "uses": [
    "vscode",
    "bat",
    "obsidian",
    "fleet",
    "sublime"
   ],
   "roles": 58,
   "scopes": 131
  },
  "treesitter": {
   "uses": [
    "nvim"
   ],
   "roles": 58,
   "scopes": 61
  },
  "vim": {
   "uses": [
    "nvim"
   ],
   "roles": 25,
   "scopes": 37
  },
  "lsp": {
   "uses": [
    "nvim",
    "vscode"
   ],
   "roles": 21,
   "scopes": 21
  },
  "jetbrains": {
   "uses": [
    "jetbrains"
   ],
   "roles": 31,
   "scopes": 43
  },
  "emacs": {
   "uses": [
    "emacs"
   ],
   "roles": 32,
   "scopes": 36
  }
 }
};
